

services:

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y docker.io &&
        exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "
    networks:
      - dev-net
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev-net

  laravel:
    image: php:8.2-cli # Or use a more generic PHP image with Composer
    container_name: laravel
    tty: true
    stdin_open: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    # depends_on:
    #   - mysql
    user: root
    command: >
      sh -c "
      apt-get update && apt-get install -y curl unzip &&
      curl -sS https://getcomposer.org/installer | php &&
      mv composer.phar /usr/local/bin/composer &&
      cd /var/www/ProjectGestor/APP_Projects && docker-php-ext-install pdo_mysql &&
      php artisan serve --host=0.0.0.0 
      "
    networks:
      - dev-net
    


volumes:
  jenkins_home:
  mysql_data:

networks:
  dev-net:
    driver: bridge
